APP:
  #INTERACTIVE: true
  EXPIRE_DAYS_THRESHOLD: 30
  #ZULIP_BOT_FILE: ".zuliprc"
  #ZULIP_STREAM: "domain-expiry-tracking"
  #ZULIP_ERROR_STREAM: "script-errors"
  #DEBUG: true
  DOMAINS:
    - "example.co.uk"
    - "example.com"
  NOTIFICATIONS:
    - "Discord"
  #  - "ZulipAPI"
  #  - "Email"
  #SCRIPT_MONITORING:
  #  - 'Zabbix'
  #ZABBIX_CONFIG_FILE: "/etc/zabbix/zabbix_agent2.conf"
  DISCORD_WEBHOOK: ""
  DISCORD_WEBHOOK_COMPLETION: ""
  DISCORD_WEBHOOK_ERROR: ""
  #SERVER_NAME: "server.example.com"
  #SMTP_SERVER: "smtp.example.com"
  #SMTP_PORT: 25
  #SMTP_FROM: "no-reply@example.com"
  #SMTP_SEND_TO: "example@example.com"